In [2]:
import numpy as np

In [3]:
valoraciones = np.array([[8,7,8,5],[2,6,8,1],[8,8,9,5]])
valoraciones

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [4]:
valoraciones[0][1]

7

In [5]:
valoraciones[0,1]

7

In [24]:
valoraciones2 = np.array([[[8,7,8,5],[2,5,5,2]],[[2,6,8,4],[8,9,7,4]],[[8,8,9,3],[10,9,10,8]]])

In [25]:
valoraciones2

array([[[ 8,  7,  8,  5],
        [ 2,  5,  5,  2]],

       [[ 2,  6,  8,  4],
        [ 8,  9,  7,  4]],

       [[ 8,  8,  9,  3],
        [10,  9, 10,  8]]])

In [26]:
valoraciones2[0,1,2]

5

In [27]:
np.zeros((3,2,4,10,5))

array([[[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          ...,
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          ...,
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          ...,
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          ...,
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          ...,
          [0., 0., 0., 0., 0.],
          [0., 0., 

In [28]:
valoraciones2 + np.ones((3,2,4))

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  6.,  6.,  3.]],

       [[ 3.,  7.,  9.,  5.],
        [ 9., 10.,  8.,  5.]],

       [[ 9.,  9., 10.,  4.],
        [11., 10., 11.,  9.]]])

In [29]:
valoraciones2

array([[[ 8,  7,  8,  5],
        [ 2,  5,  5,  2]],

       [[ 2,  6,  8,  4],
        [ 8,  9,  7,  4]],

       [[ 8,  8,  9,  3],
        [10,  9, 10,  8]]])

In [30]:
np.mean(valoraciones2)

6.458333333333333

In [31]:
np.mean(valoraciones2,axis=0)

array([[6.        , 7.        , 8.33333333, 4.        ],
       [6.66666667, 7.66666667, 7.33333333, 4.66666667]])

In [32]:
np.mean(valoraciones2,axis=1)

array([[5. , 6. , 6.5, 3.5],
       [5. , 7.5, 7.5, 4. ],
       [9. , 8.5, 9.5, 5.5]])

In [33]:
np.mean(valoraciones2,axis=2)

array([[7.  , 3.5 ],
       [5.  , 7.  ],
       [7.  , 9.25]])

In [34]:
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12], (3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [36]:
np.median(df["Columa1"])

NameError: name 'df' is not defined

In [38]:
np.random.rand(2,2)

array([[0.61781087, 0.85599706],
       [0.673784  , 0.70419713]])