In [6]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

df = pd.read_csv("D:/Python/achieves/2008.csv", nrows = 100000)
#eliminar todos los datos faltantes de las columnas a graficar(inplace)
df = df[["ArrDelay","DepDelay","Distance","AirTime"]].dropna()

In [7]:
Xscaled = preprocessing.scale(df)
Xscaled

array([[-0.63713243, -0.08247884,  0.40657043,  0.4452521 ],
       [-0.12045009,  0.3068154 ,  0.40657043,  0.38990966],
       [ 0.26706167, -0.08247884, -0.26709367, -0.29264705],
       ...,
       [ 1.84940134,  2.18250582,  0.53445243,  0.31611975],
       [ 0.17018373,  0.37759617,  0.53445243,  0.1869874 ],
       [ 0.17018373, -0.25943077,  0.53445243,  0.22388235]])

In [8]:
#Promedio por columna
Xscaled.mean(axis=0)

array([2.47651119e-17, 1.07267490e-17, 1.19506063e-16, 1.01364179e-16])

In [9]:
#Calculo de la desviacion estandar
#se convierten todas las variables en una nueva escala
# la cual esta centrada en el 0 y tiene una desviacion
#estandar de 1 y esto se hace por que es muy util
#
Xscaled.std(axis=0)

array([1., 1., 1., 1.])

In [10]:
df.iloc[2]

ArrDelay     14.0
DepDelay      8.0
Distance    515.0
AirTime      76.0
Name: 2, dtype: float64

In [11]:
Xscaled[2]

array([ 0.26706167, -0.08247884, -0.26709367, -0.29264705])

In [13]:
#este tipo de preprocesamiento altera la escala de las
#variables pero esto es muy importante en caso de tener
# muchos outliers
min_max_scaler = preprocessing.MinMaxScaler([0,10])
X_train_minmax = min_max_scaler.fit_transform(df)
X_train_minmax

array([[0.77199282, 0.92857143, 3.15557514, 2.91316527],
       [1.05924596, 1.125     , 3.15557514, 2.82913165],
       [1.27468582, 0.92857143, 1.85544293, 1.79271709],
       ...,
       [2.15439856, 2.07142857, 3.4023799 , 2.71708683],
       [1.22082585, 1.16071429, 3.4023799 , 2.5210084 ],
       [1.22082585, 0.83928571, 3.4023799 , 2.57703081]])

In [14]:
#transformar variables no numericas en variables dam
df = pd.read_csv("D:/Python/achieves/2008.csv", nrows = 100)
#la funcion get_dummies crea una tabla en la cual se 
#muestra los diferentes origenes de los vuelos y 
# muestra 1 o 0 dependiendo de donde salio el vuelo
pd.get_dummies(df["Origin"])

IAD  IND  ISP  JAN  JAX  LAS
0     1    0    0    0    0    0
1     1    0    0    0    0    0
2     0    1    0    0    0    0
3     0    1    0    0    0    0
4     0    1    0    0    0    0
..  ...  ...  ...  ...  ...  ...
95    0    0    0    0    0    1
96    0    0    0    0    0    1
97    0    0    0    0    0    1
98    0    0    0    0    0    1
99    0    0    0    0    0    1

[100 rows x 6 columns]